config/routes.rb
Rails.application.routes.draw do
  resources :minimages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/minimage.rb
class Minimage < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumbnails, resize_to_fill: [50, 50]
  end

  has_many_attached :images

  validates :title, presence: true

  def image_base64
    return base64 unless base64.nil?

    update base64: Base64.encode64(image.download)

    base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    redirect_to minimages_path    
  end
end

app/controllers/concerns/resizing_concern.rb
module ResizingConcern
  
  extend ActiveSupport::Concern

  def resizing_image(image_params)
    ActionDispatch::Http::UploadedFile.new({
      tempfile: begin
        ImageProcessing::Vips
          .source(image_params.tempfile)
          .convert(:webp)
          .resize_to_fit(600, 420)
          .call
        rescue
          ImageProcessing::MiniMagick
            .source(image_params.tempfile)
            .convert(:webp)
            .resize_to_fit(600, 420)
            .call
        end,
      type: "image/webp",
      head: "Content-Disposition: form-data; name='minimage[image]'",
      filename: "#{File.basename(image_params.original_filename, ".*")}.webp" 
    })

  rescue
    image_params
  end

  def base64_image(image_params)
    Base64.encode64(File.open(image_params.tempfile).read)
  rescue
    nil
  end
end

app/controllers/minimages_controller.rb
class MinimagesController < ApplicationController
  include ResizingConcern
  skip_before_action :verify_authenticity_token
  before_action :set_minimage, only: %i[ show edit update destroy ]
  before_action lambda { params[:image] = resizing_image(params[:image]) }, only: :create
  before_action lambda { params[:base64] = base64_image(params[:image]) }, only: :create

  # GET /minimages or /minimages.json
  def index
    @minimages = Minimage.all
  end

  # GET /minimages/1 or /minimages/1.json
  def show
  end

  # GET /minimages/new
  def new
    @minimage = Minimage.new
  end

  # GET /minimages/1/edit
  def edit
  end

  # POST /minimages or /minimages.json
  def create
    @minimage = Minimage.new(minimage_params)
    if @minimage.save
      redirect_to minimages_url, notice: "Minimage was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /minimages/1 or /minimages/1.json
  def update
    if @minimage.update(minimage_params)
      redirect_to minimage_url(@minimage), notice: "Minimage was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /minimages/1 or /minimages/1.json
  def destroy
    @minimage.destroy

    redirect_to minimages_url, notice: "Minimage was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minimage
      @minimage = Minimage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def minimage_params
      params.permit(
        :title,
        :description,
        :image,
        :base64,
        images: []
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def horizontal_space
    "<div class='pt-4'></div>".html_safe
  end
end

app/helpers/components/breadcrumb_helper.rb
module Components::BreadcrumbHelper
  def breadcrumb(items)
    content_tag "sl-breadcrumb", class: "pb-4", variant: :neutral do
      (items || []).map do |item|
        concat breadcrumb_item(item)
      end
    end
  end

  def breadcrumb_item(item)
    content_tag "sl-breadcrumb-item", href: item[:href] do
      item[:label]
    end
  end
end

app/helpers/components/flash_message_helper.rb
module Components::FlashMessageHelper
  def success_message(message)
    content_tag "sl-alert", variant: :success, open: true, clasable: true, class: "alert-closable" do
      concat content_tag("sl-icon", "", slot: :icon, name: "check2-circle")
      concat content_tag("span", message)
    end
  end
end

app/helpers/components/form_helper.rb
module Components::FormHelper
  def form(**attr, &block)
    content_tag(
      :form, 
      method: attr[:method] || :post,
      action: attr[:action] || url_for(controller: "minimages", action: "create"),
      accept_charset: "UTF-8",
      enctype: attr[:enctype] || "",
      class: "input-validation-required pt-4"
    ) do
      concat hidden_input
      concat(capture(&block))
    end
  end

  def errors_form(model = nil)
    content_tag "sl-alert", variant: :warning, open: true, clasable: nil, class: "alert-closable" do
      concat content_tag("sl-icon", "", slot: :icon, name: "exclamation-triangle")
      concat full_message_errors(model.errors)
    end
  end

  def full_message_errors(errors)
    content_tag "ul" do
      errors.each do |error|
        concat("<li>#{error.full_message}</li>".html_safe)
      end
    end
  end

  def hidden_input(model = nil)
    content_tag :input, "", type: :hidden, name: :authenticity_token, value: form_authenticity_token
  end

  def text_input(model = nil, field, **attr)
    content_tag "sl-input", "", name: "#{model&.class&.name&.downcase}[#{field}]", label: field, value: model.send(field)
  end

  def area_input(model = nil, field, **attr)
    content_tag "sl-textarea", "", name: "#{model&.class&.name&.downcase}[#{field}]", label: field, value: model.send(field)
  end

  def file_input(model = nil, field, **attr)
    content_tag "input", "", type: "file", name: "#{model&.class&.name&.downcase}[#{field}]", label: field, value: model.send(field), accept: "image/*", style: "padding: 10px 0px 10px 0px", multiple: attr[:multiple] || false
  end

  def action_form
    content_tag :div, class: "flex gap-4" do
      concat submit_button
      concat back_button
    end
  end

  def submit_button
    content_tag "sl-button", type: :submit, variant: :neutral, data: { optional: nil, valid: nil } do
      "Submit"
    end
  end

  def back_button
    content_tag "sl-button", type: :button, href: "javascript:history.back()", variant: :default, data: { optional: nil, valid: nil } do
      "Reset"
    end
  end
end

app/helpers/components/link_helper.rb
module Components::LinkHelper
  def link(action)
    content_tag("sl-button", size: 'small', href: action[:href]) do
      action[:label]
    end
  end
end

app/helpers/components/minimage_card_helper.rb
module Components::MinimageCardHelper
  def minimage_card(model)
      content_tag(
        "img", 
        "", 
        id: dom_id(model),
        # src: url_for(model.image), 
        src: "data:image/webp;base64,#{model.image_base64}",
        class: "gallery-img", 
        alt: model.title
        )
  end
end

app/helpers/components/title_helper.rb
module Components::TitleHelper
  def title(page_title, actions = [] )
    tag.div class: "title" do
      concat content_tag(:h1, page_title)
      concat title_actions(actions)
    end
  end

  def title_actions(actions)
    tag.div class: "content_action" do
      actions.map do |action|
        concat link(action)
      end
    end
  end
end

app/helpers/minimages_helper.rb
module MinimagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsImage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link
      rel="stylesheet"
      media="(prefers-color-scheme:light)"
      href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.12.0/cdn/themes/light.css"
    />
    <link
      rel="stylesheet"
      media="(prefers-color-scheme:dark)"
      href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.12.0/cdn/themes/dark.css"
      onload="document.documentElement.classList.add('sl-theme-dark');"
    />
  </head>

  <body>
    <%= yield %>

    <script type="module" src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.12.0/cdn/shoelace-autoloader.js"></script>
  </body>
</html>

app/views/minimages/_form.html.erb
<%= form model: minimage, enctype: "multipart/form-data" do %>
  <% if minimage.errors.any? %>
    <%= errors_form minimage %>
  <% end %>
  <%= horizontal_space %>
  <%= text_input minimage, :title %>
  <%= file_input minimage, :image %>
  <%= area_input minimage, :description %>
  <%= file_input minimage, :images, multiple: true %>

  <%= action_form %>
<% end %>

app/views/minimages/_minimage.html.erb
<%= minimage_card minimage %>

app/views/minimages/edit.html.erb
<h1>Editing minimage</h1>

<%= render "form", minimage: @minimage %>

<br>

<div>
  <%= link_to "Show this minimage", @minimage %> |
  <%= link_to "Back to minimages", minimages_path %>
</div>

app/views/minimages/index.html.erb
<%= title :Minimages, [
    { label: "New minimage", href: new_minimage_path }
] %>

<div>Total pictures: <%= @minimages.count %></div>

<%= horizontal_space %>
<%= success_message(notice) if notice.present? %>
<%= horizontal_space %>

<div id="minimages" class="gallery">
  <%= render @minimages %>
</div>

app/views/minimages/new.html.erb
<%= title :Minimages %>

<%= breadcrumb [
  { label: "Home", href: "/" },
  { label: "Minimages", href: minimages_path },
  { label: "new", href: "#" }
] %>

<%= render "form", minimage: @minimage %>

app/views/minimages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @minimage %>

<div>
  <%= link_to "Edit this minimage", edit_minimage_path(@minimage) %> |
  <%= link_to "Back to minimages", minimages_path %>

  <%= button_to "Destroy this minimage", @minimage, method: :delete %>
</div>